[Config]
MinimumVersion=25

[Distribution]
Distribution=ubuntu
Release=noble
Architecture=x86-64
RepositoryKeyCheck=yes
Repositories=universe

[Output]
Format=disk
Output=homenode-development
CompressOutput=no
ManifestFormat=json
RepartDirectories=mkosi.repart

[Content]
Packages=systemd,systemd-sysv,udev,linux-image-generic,grub-pc-bin,grub-efi-amd64-bin
ExtraTrees=overlay
Bootable=yes
Bootloader=grub
BiosBootloader=grub
UnifiedKernelImages=no
Autologin=no
RootPassword=hashed:!
KernelCommandLine=ro console=ttyS0
FinalizeScripts=mkosi.finalize

[Build]
BuildSources=guest:guest,overlay:overlay
WithNetwork=no
Incremental=no
