import { test, expect, type Page } from '@playwright/test'
import { execFileSync } from 'node:child_process'

async function authenticator(page: Page) {
  const cdp = await page.context().newCDPSession(page)
  await cdp.send('WebAuthn.enable')
  await cdp.send('WebAuthn.addVirtualAuthenticator', { options: {
    protocol: 'ctap2', transport: 'internal', hasResidentKey: true,
    hasUserVerification: true, isUserVerified: true, automaticPresenceSimulation: true,
  } })
}

test('enroll, pair with limited access, revoke, sign in, and recover', async ({ page, browser }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  const output = execFileSync('../bin/homenode', ['setup-code', '--state-dir', process.env.HOMENODE_TEST_STATE!], { encoding: 'utf8' })
  const code = output.trim().split('\n').at(-1)!
  await authenticator(page)
  await page.goto('/')
  await page.getByLabel('Device name', { exact: true }).fill('Owner laptop')
  await page.getByLabel('Enrollment code').fill(code)
  await page.getByRole('button', { name: 'Create a passkey', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Save these codes' })).toBeVisible()
  const recovery = await page.locator('.recovery-codes code').first().textContent()
  await expect(page.locator('.recovery-codes code')).toHaveCount(8)
  await page.getByRole('button', { name: 'I saved my recovery codes' }).click()
  await expect(page.getByRole('heading', { name: 'Your home server' })).toBeVisible()
  await expect(page.locator('.check-row')).toHaveCount(8)
  await expect(page.getByRole('heading', { name: 'External backup', exact: true })).toBeVisible()
  await expect(page.getByText('No acknowledged external backup is recorded.')).toBeVisible()
  await expect(page.getByText('Weekly backup reminder: create your first external backup.')).toBeVisible()
  // Transport/UI fixture: mocked backup operations do not prove disk backup.
  const repositoryId = 'a'.repeat(64)
  let approvalBody = '', approvalKey = '', backupRequests = 0
  await page.route('**/api/v1/backups/configuration', route => route.fulfill({ json: { enabled: true, repositoryId } }))
  await page.route('**/api/v1/backups/approval', async route => {
    approvalBody = route.request().postData()!; approvalKey = route.request().headers()['idempotency-key']
    expect(JSON.parse(approvalBody)).toEqual({ repositoryId })
    expect(approvalBody).not.toContain('fixture-password')
    await route.fulfill({ json: { options: { publicKey: { challenge: 'YWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXo', rpId: 'localhost', userVerification: 'required', timeout: 10000 } }, challengeToken: 'backup-fixture-challenge' } })
  })
  await page.route('**/api/v1/auth/approval/finish', async route => {
    expect(route.request().headers()['x-approval-challenge']).toBe('backup-fixture-challenge')
    expect(JSON.parse(route.request().postData()!).type).toBe('public-key')
    await route.fulfill({ json: { approvalToken: 'backup-fixture-grant' } })
  })
  await page.route('**/api/v1/backups', async route => {
    backupRequests++
    const headers = route.request().headers(), bytes = route.request().postDataBuffer()!
    expect(headers['content-type']).toBe('application/vnd.homenode.backup-credential')
    expect(headers['idempotency-key']).toBe(approvalKey)
    expect(headers['x-action-approval']).toBe('backup-fixture-grant')
    const length = bytes.readUInt32BE(0)
    expect(bytes.subarray(4, 4 + length).toString()).toBe(approvalBody)
    expect(bytes.subarray(4 + length).toString()).toBe('fixture-password-π')
    await route.fulfill({ status: 202, json: { jobId: 'backup-fixture-job', status: 'preparing' } })
  })
  await page.locator('nav').getByRole('button', { name: 'Settings', exact: false }).click()
  await expect(page.getByText('No acknowledged external backup is recorded.')).toBeVisible()
  await page.getByLabel('Backup reminder interval (days)').fill('14')
  await page.getByRole('button', { name: 'Save reminder interval' }).click()
  await expect(page.getByText('Backup reminder interval saved.')).toBeVisible()
  expect(await page.evaluate(async () => (await (await fetch('/api/v1/backups/outcomes')).json()).reminder.intervalDays)).toBe(14)
  await page.locator('nav').getByRole('button', { name: 'Overview', exact: false }).click()
  await page.locator('nav').getByRole('button', { name: 'Settings', exact: false }).click()
  await expect(page.getByLabel('Backup reminder interval (days)')).toHaveValue('14')
  await page.getByLabel('Repository password').fill('fixture-password-π')
  await page.getByRole('button', { name: 'Verify passkey and start backup' }).click()
  await expect(page.getByText('Backup job backup-fixture-job started.', { exact: false })).toBeVisible()
  await expect(page.getByLabel('Repository password')).toHaveValue('')
  expect(backupRequests).toBe(1)
  await page.evaluate(() => Object.defineProperty(navigator.credentials, 'get', { configurable: true, value: async () => { throw new DOMException('Fixture cancelled', 'NotAllowedError') } }))
  await page.getByLabel('Repository password').fill('cancelled-secret')
  await page.getByRole('button', { name: 'Verify passkey and start backup' }).click()
  await expect(page.getByRole('alert')).toBeVisible()
  await expect(page.getByLabel('Repository password')).toHaveValue('')
  expect(backupRequests).toBe(1)
  await page.evaluate(() => Reflect.deleteProperty(navigator.credentials, 'get'))
  for (const refused of [false, true]) {
  const resumeJob = (refused ? 'B' : 'A').repeat(24)
  let resumeAccepted = false, resumeRequests = 0, resumeKey = ''
  await page.route('**/api/v1/backups/outcomes', route => route.fulfill({ json: {
    schema: 1, current: refused ? null : { status: 'published', publishedAt: 10 }, lastPublished: { status: 'published', publishedAt: 10 }, workerCompletion: refused && !resumeAccepted ? 'refused' : 'complete', resumeJobId: resumeAccepted ? '' : resumeJob, reminder: { state: 'unavailable', intervalDays: 0 },
  } }))
  await page.route(`**/api/v1/backups/${resumeJob}/resume/approval`, async route => {
    expect(route.request().postData()).toBe('{}')
    resumeKey = route.request().headers()['idempotency-key']
    await route.fulfill({ json: { options: { publicKey: { challenge: 'YWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXo', rpId: 'localhost', userVerification: 'required', timeout: 10000 } }, challengeToken: 'backup-fixture-challenge' } })
  })
  await page.route(`**/api/v1/backups/${resumeJob}/resume`, async route => {
    resumeRequests++
    expect(route.request().postData()).toBe('{}')
    expect(route.request().headers()['idempotency-key']).toBe(resumeKey)
    expect(route.request().headers()['x-action-approval']).toBe('backup-fixture-grant')
    expect(route.request().headers()['content-type']).toBe('application/json')
    resumeAccepted = true
    await route.fulfill({ status: 202, json: { jobId: resumeJob, status: 'restoring' } })
  })
  await page.getByRole('button', { name: 'Refresh backup status' }).click()
  if (refused) await expect(page.getByText('The backup repository was refused before runtime acquisition.', { exact: false })).toBeVisible()
  await expect(page.getByText('Backup reminder timing is unavailable.', { exact: false })).toBeVisible()
  await expect(page.getByLabel('Backup reminder interval (days)')).toHaveValue('7')
  expect((await (await page.request.get('/api/v1/backups/outcomes')).json()).reminder.intervalDays).toBe(14)
  await page.evaluate(() => Object.defineProperty(navigator.credentials, 'get', { configurable: true, value: async () => { throw new DOMException('Resume cancelled', 'NotAllowedError') } }))
  await page.getByRole('button', { name: 'Verify passkey and resume workloads' }).click()
  await expect(page.getByRole('alert').filter({ hasText: 'Resume cancelled' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Verify passkey and resume workloads' })).toBeEnabled()
  expect(resumeRequests).toBe(0)
  await page.evaluate(() => Reflect.deleteProperty(navigator.credentials, 'get'))
  await page.getByRole('button', { name: 'Verify passkey and resume workloads' }).click()
  await expect(page.getByText('Workload restoration started.', { exact: false })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Verify passkey and resume workloads' })).toHaveCount(0)
  expect(resumeRequests).toBe(1)
  await page.unroute('**/api/v1/backups/outcomes')
  await page.unroute(`**/api/v1/backups/${resumeJob}/resume/approval`)
  await page.unroute(`**/api/v1/backups/${resumeJob}/resume`)
  }
  await page.unroute('**/api/v1/backups/configuration')
  await page.unroute('**/api/v1/backups/approval')
  await page.unroute('**/api/v1/auth/approval/finish')
  await page.unroute('**/api/v1/backups')
  await page.locator('nav').getByRole('button', { name: 'Overview', exact: false }).click()
  await page.locator('nav').getByRole('button', { name: 'Settings', exact: false }).click()


  await page.route('**/api/v1/backups/outcomes', route => route.fulfill({ json: {
    schema: 1, current: { status: 'unknown', publishedAt: 0 }, lastPublished: { status: 'published', publishedAt: 10 }, reminder: { state: 'overdue', intervalDays: 7, dueAt: 604810 },
  } }))
  await page.getByRole('button', { name: 'Refresh backup status' }).click()
  await expect(page.getByRole('status').filter({ hasText: 'latest backup outcome is uncertain' })).toBeVisible()
  await expect(page.getByText('Backup reminder: the last acknowledged publication is at least 7 days old.')).toBeVisible()
  await expect(page.getByText('Last acknowledged publication:', { exact: false })).toBeVisible()
  await page.unroute('**/api/v1/backups/outcomes')
  await page.route('**/api/v1/backups/outcomes', route => route.fulfill({ json: {
    schema: 1, current: { status: 'published', publishedAt: 10 }, lastPublished: { status: 'published', publishedAt: 10 }, workerCompletion: 'uncertain',
  } }))
  await page.getByRole('button', { name: 'Refresh backup status' }).click()
  await expect(page.getByRole('status')).toContainText('Backup worker completion is uncertain')
  await expect(page.getByText('Last acknowledged publication:', { exact: false })).toBeVisible()
  await page.unroute('**/api/v1/backups/outcomes')
  await page.route('**/api/v1/backups/outcomes', route => route.fulfill({ status: 503, json: { error: 'unavailable' } }))
  await page.getByRole('button', { name: 'Refresh backup status' }).click()
  await expect(page.getByRole('alert').filter({ hasText: 'Backup status is unavailable' })).toBeVisible()
  await expect(page.getByText('Last acknowledged publication:', { exact: false })).toHaveCount(0)
  await page.unroute('**/api/v1/backups/outcomes')
  await page.locator('nav').getByRole('button', { name: 'Overview', exact: false }).click()
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.setViewportSize({ width: 1280, height: 900 })
  await page.locator('nav').getByRole('button', { name: 'Files', exact: false }).click()
  await expect(page.getByRole('heading', { name: 'Your files' })).toBeVisible()
  await page.locator('nav').getByRole('button', { name: 'Jobs', exact: false }).click()
  await expect(page.getByRole('heading', { name: 'Convert a video' })).toBeVisible()
  await page.locator('nav').getByRole('button', { name: 'AI', exact: false }).click()
  await page.getByRole('button', { name: 'New conversation' }).click()
  await expect(page.getByLabel('Message', { exact: true })).toBeVisible()
  const conversationId = await page.locator('.conversation-picker select').inputValue()
  // UI reload fixture only; backend pending-intent reporting has Go coverage.
  await page.route('**/api/v1/ai/conversations', async route => {
    if (route.request().method() !== 'GET') return route.continue()
    return route.fulfill({ json: [{ id: conversationId, title: 'Pending cleanup', createdAt: 1, deletionPending: true }] })
  })
  await page.reload()
  await page.locator('nav').getByRole('button', { name: 'AI', exact: false }).click()
  await page.locator('.conversation-picker select').selectOption(conversationId)
  await expect(page.getByRole('status')).toContainText('Deletion is pending')
  await expect(page.getByLabel('Message', { exact: true })).not.toBeVisible()
  await expect(page.getByRole('button', { name: 'Delete conversation', exact: true })).toBeDisabled()
  await page.unroute('**/api/v1/ai/conversations')
  await page.reload()
  await page.locator('nav').getByRole('button', { name: 'AI', exact: false }).click()
  await page.locator('.conversation-picker select').selectOption(conversationId)
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: 'Delete conversation', exact: true }).click()
  await expect(page.getByLabel('Message', { exact: true })).not.toBeVisible()

  await page.getByRole('button', { name: 'Devices', exact: false }).click()
  await page.getByLabel('Device name', { exact: true }).fill('Paired phone')
  await page.getByLabel('JOBS', { exact: true }).uncheck()
  await page.getByLabel('AI', { exact: true }).uncheck()
  await page.getByRole('button', { name: 'Create invitation' }).click()
  const invitation = await page.locator('.invitation code').textContent()
  const phoneContext = await browser.newContext()
  const phone = await phoneContext.newPage()
  await authenticator(phone)
  await phone.goto('http://localhost:18787/')
  await phone.getByRole('button', { name: 'Pair a device' }).click()
  await phone.getByLabel('Enrollment code').fill(invitation!)
  await phone.getByRole('button', { name: 'Create a passkey', exact: true }).click()
  await expect(phone.getByRole('heading', { name: 'Your home server' })).toBeVisible()
  await expect(phone.getByRole('heading', { name: 'External backup', exact: true })).toHaveCount(0)
  const denial = await phone.evaluate(async () => (await fetch('/api/v1/devices')).status)
  expect(denial).toBe(403)
  await phone.locator('nav').getByRole('button', { name: 'Settings', exact: false }).click()
  await expect(phone.getByRole('heading', { name: 'External backup', exact: true })).toHaveCount(0)
  expect(await phone.evaluate(async () => (await fetch('/api/v1/backups/outcomes')).status)).toBe(403)
  await page.reload()
  await page.getByRole('button', { name: 'Devices', exact: false }).click()
  page.once('dialog', dialog => dialog.accept())
  await page.locator('.device-row').filter({ hasText: 'Paired phone' }).getByRole('button', { name: 'Revoke' }).click()
  await expect(page.locator('.device-row').filter({ hasText: 'Paired phone' })).toContainText('Revoked')
  expect(await phone.evaluate(async () => (await fetch('/api/v1/session')).status)).toBe(401)
  await page.getByRole('button', { name: 'Settings', exact: false }).click()
  await page.getByRole('button', { name: 'Preview report' }).click()
  await expect(page.locator('.diagnostics')).toContainText('[redacted]')
  await page.getByRole('button', { name: 'Sign out', exact: true }).click()
  await page.getByRole('button', { name: 'Sign in with a passkey' }).click()
  await expect(page.getByRole('heading', { name: 'Your home server' })).toBeVisible()
  const recoveryContext = await browser.newContext()
  const recovered = await recoveryContext.newPage()
  await authenticator(recovered)
  await recovered.goto('http://localhost:18787/')
  await recovered.getByRole('button', { name: 'Use a recovery code' }).click()
  await recovered.getByLabel('Recovery code', { exact: true }).fill(recovery!)
  await recovered.getByRole('button', { name: 'Create a passkey', exact: true }).click()
  await expect(recovered.getByRole('heading', { name: 'Save these codes' })).toBeVisible()
  expect(await page.evaluate(async () => (await fetch('/api/v1/session')).status)).toBe(401)
  await recovered.getByRole('button', { name: 'I saved my recovery codes' }).click()
  await expect(recovered.getByRole('heading', { name: 'Your home server' })).toBeVisible()
  expect(errors).toEqual([])
  await phoneContext.close(); await recoveryContext.close()
})
