import { test, expect, type Page } from '@playwright/test'
import { execFileSync } from 'node:child_process'

async function authenticator(page: Page) {
  const cdp = await page.context().newCDPSession(page)
  await cdp.send('WebAuthn.enable')
  await cdp.send('WebAuthn.addVirtualAuthenticator', { options: {
    protocol: 'ctap2', transport: 'internal', hasResidentKey: true,
    hasUserVerification: true, isUserVerified: true, automaticPresenceSimulation: true,
  } })
}

test('enroll, pair with limited access, revoke, sign in, and recover', async ({ page, browser }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  const output = execFileSync('../bin/homenode', ['setup-code', '--state-dir', process.env.HOMENODE_TEST_STATE!], { encoding: 'utf8' })
  const code = output.trim().split('\n').at(-1)!
  await authenticator(page)
  await page.goto('/')
  await page.getByLabel('Device name', { exact: true }).fill('Owner laptop')
  await page.getByLabel('Enrollment code').fill(code)
  await page.getByRole('button', { name: 'Create a passkey', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Save these codes' })).toBeVisible()
  const recovery = await page.locator('.recovery-codes code').first().textContent()
  await expect(page.locator('.recovery-codes code')).toHaveCount(8)
  await page.getByRole('button', { name: 'I saved my recovery codes' }).click()
  await expect(page.getByRole('heading', { name: 'Your home server' })).toBeVisible()
  await expect(page.locator('.check-row')).toHaveCount(8)
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.setViewportSize({ width: 1280, height: 900 })
  await page.locator('nav').getByRole('button', { name: 'Files', exact: false }).click()
  await expect(page.getByRole('heading', { name: 'Your files' })).toBeVisible()
  await page.locator('nav').getByRole('button', { name: 'Jobs', exact: false }).click()
  await expect(page.getByRole('heading', { name: 'Convert a video' })).toBeVisible()
  await page.locator('nav').getByRole('button', { name: 'AI', exact: false }).click()
  await page.getByRole('button', { name: 'New conversation' }).click()
  await expect(page.getByLabel('Message', { exact: true })).toBeVisible()
  const conversationId = await page.locator('.conversation-picker select').inputValue()
  // UI reload fixture only; backend pending-intent reporting has Go coverage.
  await page.route('**/api/v1/ai/conversations', async route => {
    if (route.request().method() !== 'GET') return route.continue()
    return route.fulfill({ json: [{ id: conversationId, title: 'Pending cleanup', createdAt: 1, deletionPending: true }] })
  })
  await page.reload()
  await page.locator('nav').getByRole('button', { name: 'AI', exact: false }).click()
  await page.locator('.conversation-picker select').selectOption(conversationId)
  await expect(page.getByRole('status')).toContainText('Deletion is pending')
  await expect(page.getByLabel('Message', { exact: true })).not.toBeVisible()
  await expect(page.getByRole('button', { name: 'Delete conversation', exact: true })).toBeDisabled()
  await page.unroute('**/api/v1/ai/conversations')
  await page.reload()
  await page.locator('nav').getByRole('button', { name: 'AI', exact: false }).click()
  await page.locator('.conversation-picker select').selectOption(conversationId)
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: 'Delete conversation', exact: true }).click()
  await expect(page.getByLabel('Message', { exact: true })).not.toBeVisible()

  await page.getByRole('button', { name: 'Devices', exact: false }).click()
  await page.getByLabel('Device name', { exact: true }).fill('Paired phone')
  await page.getByLabel('JOBS', { exact: true }).uncheck()
  await page.getByLabel('AI', { exact: true }).uncheck()
  await page.getByRole('button', { name: 'Create invitation' }).click()
  const invitation = await page.locator('.invitation code').textContent()
  const phoneContext = await browser.newContext()
  const phone = await phoneContext.newPage()
  await authenticator(phone)
  await phone.goto('http://localhost:18787/')
  await phone.getByRole('button', { name: 'Pair a device' }).click()
  await phone.getByLabel('Enrollment code').fill(invitation!)
  await phone.getByRole('button', { name: 'Create a passkey', exact: true }).click()
  await expect(phone.getByRole('heading', { name: 'Your home server' })).toBeVisible()
  const denial = await phone.evaluate(async () => (await fetch('/api/v1/devices')).status)
  expect(denial).toBe(403)
  await page.reload()
  await page.getByRole('button', { name: 'Devices', exact: false }).click()
  page.once('dialog', dialog => dialog.accept())
  await page.locator('.device-row').filter({ hasText: 'Paired phone' }).getByRole('button', { name: 'Revoke' }).click()
  await expect(page.locator('.device-row').filter({ hasText: 'Paired phone' })).toContainText('Revoked')
  expect(await phone.evaluate(async () => (await fetch('/api/v1/session')).status)).toBe(401)
  await page.getByRole('button', { name: 'Settings', exact: false }).click()
  await page.getByRole('button', { name: 'Preview report' }).click()
  await expect(page.locator('.diagnostics')).toContainText('[redacted]')
  await page.getByRole('button', { name: 'Sign out', exact: true }).click()
  await page.getByRole('button', { name: 'Sign in with a passkey' }).click()
  await expect(page.getByRole('heading', { name: 'Your home server' })).toBeVisible()
  const recoveryContext = await browser.newContext()
  const recovered = await recoveryContext.newPage()
  await authenticator(recovered)
  await recovered.goto('http://localhost:18787/')
  await recovered.getByRole('button', { name: 'Use a recovery code' }).click()
  await recovered.getByLabel('Recovery code', { exact: true }).fill(recovery!)
  await recovered.getByRole('button', { name: 'Create a passkey', exact: true }).click()
  await expect(recovered.getByRole('heading', { name: 'Save these codes' })).toBeVisible()
  expect(await page.evaluate(async () => (await fetch('/api/v1/session')).status)).toBe(401)
  await recovered.getByRole('button', { name: 'I saved my recovery codes' }).click()
  await expect(recovered.getByRole('heading', { name: 'Your home server' })).toBeVisible()
  expect(errors).toEqual([])
  await phoneContext.close(); await recoveryContext.close()
})
